name: CI - Build and Push Image

on:
  push:
    branches: [ "main", "dev" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentals
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Image
        run: |
          docker build -t datagrokr-intern-devops .

      - name: Tag Image
        run: |
          docker tag datagrokr-intern-devops:latest ${{ steps.login-ecr.outputs.registry }}/datagrokr-intern-devops:latest

      - name: Push Image
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/datagrokr-intern-devops:latest
